### ISSUE TITLE
MH7-WH not being recognized

### ISSUE THREAD

**Issue by yirk** [TedTolboom/com.mcohome#21]
I've just tried to add my new MCO MH7-WH's to Homey. While it can find the devices they are added as generic devices and not recognized by the MCO app.

Please let me know if I can supply any information from the devices which might shed some light on this issue. Thanks for your work!

**Comment by TedTolboom** [comment]
Can you show the ID’s of the device when added as generic device?

And a picture of the device label?

MCOHome has a lot of different ID’s related to the different regions; so likely I missed some

**Comment by yirk** [comment]
Just had a look at MH7.json and realized that the productTypeId is 1793 while Homey shows 1809 for mine. manufacturerId is the same (351) and productId is 20738.

**Comment by yirk** [comment]
<img width="318" alt="homey mco mh7" src="https://user-images.githubusercontent.com/13270518/49611651-781d3b80-f9a2-11e8-84cb-20ef3079fad2.png">

**Comment by yirk** [comment]
Do you need anything else?

**Comment by TedTolboom** [comment]
Thanks.

Can you also share a picture of the label on the back of the thermostat; to check the actual product number mentioned on the device.

**Comment by ttorlen** [comment]
![img_4264](https://user-images.githubusercontent.com/45918849/50055800-d4771c80-0153-11e9-90a4-35d0fb017bb1.jpg)

Hi Ted!

I have the same issue MH7H-EH  working fine and MH7h-WH comming upp at generic device.
<img width="1440" alt="skarmavbild 2018-12-16 kl 17 01 33" src="https://user-images.githubusercontent.com/45918849/50055845-58c99f80-0154-11e9-9a6b-0f503c6afc76.png">

**Comment by TedTolboom** [comment]
I've added the two additional Product ID's to the v1.2.1 release of this app.

@yirk I assumed you have the MH7- thermostat (without humidity)
@ttorlen added to the MH7H- thermostat (with humidity)

This version will be released to the app store asap.
I'll close this issue for now, let me know if v1.2.1 is not solving your issues

**Comment by yirk** [comment]
Sure, I will report back once I have 1.2.1. Thanks!

**Comment by TedTolboom** [comment]
@yirk Just to verify. It is correct that you MH7 thermostat doesn’t have the humidity sensor, right?

**Comment by yirk** [comment]
Yes, that is correct!

**Comment by ttorlen** [comment]
Hi Ted !

I have test 1.2.1 now and it works fine.

Thank you

//TT

Från: dT <notifications@github.com>
Svara till: "TedTolboom/com.mcohome" <reply@reply.github.com>
Datum: tisdag 1 januari 2019 12:54
Till: "TedTolboom/com.mcohome" <com.mcohome@noreply.github.com>
Kopia: Thomas Torlen <ttorlen@cisco.com>, Mention <mention@noreply.github.com>
Ämne: Re: [TedTolboom/com.mcohome] MH7-WH not being recognized (#21)


I've added the two additional Product ID's to the v1.2.1 release of this app.

@yirk<https://github.com/yirk> I assumed you have the MH7- thermostat (without humidity)
@ttorlen<https://github.com/ttorlen> added to the MH7H- thermostat (with humidity)

This version will be released to the app store asap.
I'll close this issue for now, let me know if v1.2.1 is not solving your issues

**Comment by TedTolboom** [comment]
Thanks for the feedback!

**Comment by yirk** [comment]
I finally got 1.2.1 as well and it works like a charm. Thanks a lot!!
