### ISSUE TITLE
MCOhome MH-S212 Compatibility with Homey v2

### ISSUE THREAD

**Issue by guardianhell** [TedTolboom/com.mcohome#23]

**Comment by guardianhell** [comment]
![a8e53691-d004-4612-9b95-e7abd8121e3a](https://user-images.githubusercontent.com/37662698/50574185-ae20d480-0e15-11e9-90bd-5b915299cf20.jpeg)
Hi Ted, i tried to pair homey with mco double switch module and it seems not working, need your help to make it works 👍

**Comment by Evitsu** [comment]
Hi guardian,
What do you mean u cannot pair it?
