### ISSUE TITLE
Add a switch

### ISSUE THREAD

**Issue by tanwk3** [TedTolboom/com.mcohome#26]
When adding, return retrieving command class version and return no device found.

Apparently device is added partially and not visible. Have to be removed and add again.  When adding return same issue

**Comment by justinkwk** [comment]
I have a similar issue when trying to add a z-wave plus 4 gang switch. The switch responded (all buttons blinked and switched off), but nothing was added and a message says no z-wave device was found. 

Another similar switch had no such issue and was included successfully. Any help?

**Comment by Evitsu** [comment]
Hi guys, i have had similar issues to the above mentioned. You must have homey close to the switch you are adding to your network. For me, i pluggged the power via my powerbank and i carry it with me to the switches. Try excluding the switches from the network first via settings; z-wave. Then try adding it again. This applies to all z-wave devices(the method i mean). Hope that helps.
;)
