### ISSUE TITLE
Mco MH-P220

### ISSUE THREAD

**Issue by Pim65** [TedTolboom/com.mcohome#27]
Hi Ted, this one is not recognized as a dimmer from mco, homey sets it up as a generic zwave device. But in that case i cant use it as a Dimmer

**Comment by martindedeyne** [comment]
Hi Pim, Hi Ted,
I have the same issue! I can only use my inwall dimmer as a switch... is there a fix for this bug?

**Comment by TedTolboom** [comment]
Likely MCOHome delivered a new P220 with changed ID's...

Can you post the device ID's for the P220?
Then I can update the app accordingly.

**Comment by martindedeyne** [comment]
Dear ted,

See the picture below

[image1.png]


When do you think this bug will be fixed?

Verstuurd vanaf mijn iPhone

Op 8 apr. 2019 om 17:00 heeft Ted Tolboom <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Likely MCOHome delivered a new P220 with changed ID's...

Can you post the device ID's for the P220?
Then I can update the app accordingly.

**Comment by martindedeyne** [comment]
ID: 20738

**Comment by Pim65** [comment]
Product ID:20738

**Comment by Pim65** [comment]
I see you did an update yesterday, but I still have the same issue that homey can not find an app for it and adds it as an generic z wave unit with no dimmer function.

**Comment by martindedeyne** [comment]
Dear Ted,
Could please give us an indication of when this will be resolved? If not soon, then I have to buy other dimmers. Because I want to continue upgrading my house! 

Thanks for the response!

Kind regards,
Martin

**Comment by TedTolboom** [comment]
Sorry guys, too busy times at work.
Update including the additional productTypeID has been made: v1.2.3 and is awaiting the app store approval for release.

That should solve your inclusion issues.
Once more, appologies for the late response.

**Comment by martindedeyne** [comment]
Great news Ted!

Thanks for the notification 👍


Op 5 mei 2019 om 22:09 heeft Ted Tolboom <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Sorry guys, too busy times at work.
Update including the additional productTypeID has been made: v1.2.3 and is awaiting the app store approval for release.

That should solve your inclusion issues.
Once more, appologies for the late response.
