### ISSUE TITLE
C321 - UK Shutter

### ISSUE THREAD

**Issue by pugwash71** [TedTolboom/com.mcohome#29]
First, thanks for writing the app, it was the key reason we bought Homey!

The only issue i have is with the shutter, and specifically Alexa integration. Alexa will not recognise the shutter switches. I have tried a work around using Virtual devices to create a dimmer which alexa can see and then create a flow that calls the shutter, this however is flaky at best. If there is a work around or a fix this would help massively as we are creating a 'show home' for our business using various devices around the homey hub.
Many thanks 
Nick

**Comment by TedTolboom** [comment]
Hi Nick,

I would wonder if the Alexa plugin for Homey is recognizing any shutter implementations within Homey apps correctly... Within my app, I'm using the default windowscoverings class and capabilities.

So if the proper translations are made within the Alexa plugin, it should work.
Did you check with Athom support?

Looking forward to your show home at the UK ;-P

**Comment by pugwash71** [comment]
Thanks Ted

They weren't very helpful and said use the other Alexa implementation, this is no good for our needs. I've reposted to support with your comments
On 05/05/2019 21:12:46, Ted Tolboom <notifications@github.com> wrote:
Hi Nick,
I would wonder if the Alexa plugin for Homey is recognizing any shutter implementations within Homey apps correctly... Within my app, I'm using the default windowscoverings class and capabilities.
So if the proper translations are made within the Alexa plugin, it should work.
Did you check with Athom support?
Looking forward to your show home at the UK ;-P
