### ISSUE TITLE
MH-S513 not working

### ISSUE THREAD

**Issue by margin1234** [TedTolboom/com.mcohome#35]
Hi, Thanks for a great app.
One thing though... Although the MH-S513 is listed, when I try to add they just come up as basic z-wave switches. I have a few....same on each one. Help please.....

**Comment by TedTolboom** [comment]
@margin1234 can you share a screenshot of the device ID's when added as basic Z-wave switch?

**Comment by margin1234** [comment]
Hi,
It's me Kevin. I sent that ages ago before I emailed you.

K


Kevin Chu
0435 079 392

**Comment by TedTolboom** [comment]
@margin1234 I'll close the issue; confirmed working by mail.
