### ISSUE TITLE
MH7H-WH Thermostat with VOC cards

### ISSUE THREAD

**Issue by dirkg173** [TedTolboom/com.mcohome#45]
Even though I only have the above mentioned thermostats from MCO Home in use, there are cards for VOC in the "When..." section.

Homey FW: v5.0.0
MCOHome App: v1.4.0

<img width="245" alt="Bildschirmfoto 2021-03-04 um 12 25 19" src="https://user-images.githubusercontent.com/40319629/109958175-3cd75780-7ce6-11eb-995d-6328142e7ae9.png">

EDIT 17.06.21
Still the same with:
Homey FW: v7.0.0
MCOHome App: v1.4.0
Diagnostic Report #: 132b9627-e81d-43f0-bd36-17d604eb6015

**Comment by TedTolboom** [comment]
fixed in 1.5.1
