### ISSUE TITLE
CO2 Sensor CO2 Alarm

### ISSUE THREAD

**Issue by Caros2017** [TedTolboom/com.mcohome#5]
My CO2 sensor has had values between 300ppm and 2.000ppm, but the CO2 alarm has never been triggered. According to the manual this has a default trigger value of 1.000ppm.

**Comment by Caros2017** [comment]
Any updates on this one? :)

**Comment by TedTolboom** [comment]
busted... looking into it... 
seems the report parser in the meshdriver is incorrect...

**Comment by Caros2017** [comment]
@TedTolboom, 5 minutes ago I've updated homey to 1.5.8, and suddenly the CO2 alarm is popping up!

**Comment by TedTolboom** [comment]
@Caros2017 will be fixed (triggering and resetting) in v1.1.0 (already on GH, uploaded to the app store)...

Will close this issue. Please re-open if not fixed in v1.1.0
