### ISSUE TITLE
On/off state of physical switch is not updated

### ISSUE THREAD

**Issue by lukelinsj** [TedTolboom/com.mcohome#50]
After updating homey to ver 7.0, the on/off state of a light at the physical switch is not reflected on the mcohome app on homey

**Comment by teyyuanhong** [comment]
Hi, i am also facing the same issues. Any resolution?

**Comment by dirkg173** [comment]
Just for information:

![E7AD515D-D4AA-4F1D-A479-1A01EEF16B75](https://user-images.githubusercontent.com/40319629/122647739-fdfacf80-d125-11eb-9162-17e006b4e653.jpeg)
