### ISSUE TITLE
MCO MH-S314 700 Series, MGH-C421

### ISSUE THREAD

**Issue by SPAeotec** [TedTolboom/com.mcohome#59]
Please add the id for MH-S314 (700 Series)

ManufactorerID: 351
ProducttypeID: 28737
ProductID: 28930

MH-C421 (Shutter Panel)

ManufactorerID: 351
ProducttypeID: 50209
ProductID:  20738

Thanks

**Comment by molnarg** [comment]
I have an open pull request for MH-C421 (#58). You can intall my fork to get it working.

**Comment by TedTolboom** [comment]
Fixed in v1.5.1
