### ISSUE TITLE
App test version 1.5.3: Could not get device by id

### ISSUE THREAD

**Issue by dirkg173** [TedTolboom/com.mcohome#63]
Hi @TedTolboom,
thank's for updating the app. The issue #62 "This app was terminated unexpectedly" is fixed, but there is another issue.
There is nor response between Homey app and device (MH7H).
If I change the set temperature at the thermostat, then the temperature is not updated in the app. Same when I change the mode (Manual, Auto, Off). Nothing is updated in the app.
If I change the set temperature or the mode in the Homey app, then the following error is displayed:

> **! Could not get device by id**

Restarting the app did not fix this issue.

Diagnostic report no.: f2547c64-ca3e-4bb2-88e3-326fe9ae5bec

**Comment by TedTolboom** [comment]
Thanks… one step at the time..

Should be fixed (completely) in 1.5.4

**Comment by dirkg173** [comment]
Hi Ted,
yes, this issue seems to be fixed.
At this moment I don't see any other issues in regard to the MH7H devices.

Thank you for your efforts, and in general thank you for all your great Homey apps.

BR
Dirk
