### ISSUE TITLE
MCOHome Dimmers Association Issues

### ISSUE THREAD

**Issue by Wysie** [TedTolboom/com.mcohome#69]
Hi there, I’ve written in to Homey but was asked to report the issue here instead. I noticed a bug where if I were to go into a dimmer’s advanced settings to add Node IDs for associations, I am unable to add anything that has a “.” in it. For example I can add 14, but I cannot add 14.1. If I add 14.1 and save it, in the mobile app it’ll just become 14. In the web app, I can’t even save it as a red border will appear around 14.1.

Thanks for looking into this and for building this!

**Comment by wysie** [comment]
Closing this as Ted has checked on Slack that the dimmers don't support multichannel associations.
